---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# compassanalyzer

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of compassanalyzer like so:

``` r
# install.packages("devtools")
devtools::install_github("thereallda/compassanalyzer")

```

## Quick Start
### Load package

```{r,warning=FALSE,message=FALSE}
library(tidyverse)

# if you do not have `enONE` package installed, run the following code first: 
# devtools::install_github("thereallda/enONE")
if (!requireNamespace("enONE", quietly = TRUE)) { devtools::install_github("thereallda/enONE") }
library(enONE)
library(compassanalyzer)
```


### Load data

```{r}
counts_df <- read.csv("data/Counts1.csv", row.names = 1)
meta <- read.csv("data/metadata1.csv")

# metadata for synthetic RNA
syn_id <- paste("syn",3:7, sep = "_")
syn_meta <- data.frame(
  id = syn_id,
  per = c(0.05,0.01,0.20,0,0.10)
)
```

### Filtering 

```{r}
counts_keep <- enONE::FilterLowExprGene(counts_df, 
                                 group = meta$condition,
                                 min.count = 20)
```

### Create object

```{r}
Compass <- createCompass(counts_keep,
                         bio.group = meta$condition,
                         enrich.group = meta$enrich,
                         spike.in.prefix = "^FB",
                         input.id = "Input",
                         enrich.id = "Enrich",
                         synthetic.id = syn_meta$id)

```

### Calculate Ratio

```{r}
Compass <- CompassAnalyze(Compass)
qratio_df <- getRatio(Compass, slot = "sample", filter = T)
head(qratio_df);dim(qratio_df)
```

### Synthetic RNA Calibration curve

```{r}
synScatter(ratio.df = qratio_df, syn.meta = syn_meta)
```
